
# Make a get request to get the latest position of the international space station from the opennotify api.
import clashroyale
myToken ='eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjNlN2Q2OTkwLWExYjMtNDAwOS1hMDA3LTllNGI1MjEzNDQ4MyIsImlhdCI6MTU0NjI1MjA2Niwic3ViIjoiZGV2ZWxvcGVyLzg4N2ZhMmZkLWI5MDYtZGVhOS03ZjA2LWQ1ZmFjZmRkMzdlNSIsInNjb3BlcyI6WyJyb3lhbGUiXSwibGltaXRzIjpbeyJ0aWVyIjoiZGV2ZWxvcGVyL3NpbHZlciIsInR5cGUiOiJ0aHJvdHRsaW5nIn0seyJjaWRycyI6WyI4MS4xNDQuMTMyLjE4MSJdLCJ0eXBlIjoiY2xpZW50In1dfQ.l9Nt0yEM16DlYfBTSXBFjW2WeUGzHdgBfTApZSKU91c6pYk8zpYmJiU3KzqNtr-6mowPp1Er_mE5Ba66QOUEYg'
cr = clashroyale.official_api.Client(myToken)
all_cards = cr.get_all_cards()
print(all_cards['name'])